# Generated by Django 5.1.2 on 2025-02-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon_class',
            field=models.ForeignKey(limit_choices_to={'category_code': 'icon'}, on_delete=django.db.models.deletion.CASCADE, to='restoran.masterdata'),
        ),
    ]
