# Generated by Django 5.1.2 on 2025-02-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0002_masterdata_alter_menu_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.menu')),
            ],
        ),
    ]
