# Generated by Django 5.1.2 on 2025-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0004_alter_fooditem_image_alter_fooditem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
