# Generated by Django 5.1.2 on 2025-02-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0005_fooditem_image_url_alter_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
    ]
