# Generated by Django 5.1.2 on 2025-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0008_alter_reservation_date_alter_reservation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('css_class', models.CharField(choices=[('gallery-image-one', 'Gallery Image One'), ('gallery-image-two', 'Gallery Image Two'), ('gallery-image-three', 'Gallery Image Three'), ('gallery-image-four', 'Gallery Image Four'), ('gallery-image-five', 'Gallery Image Five'), ('gallery-image-six', 'Gallery Image Six')], max_length=50)),
            ],
        ),
    ]
