# Generated by Django 5.1.2 on 2025-02-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0009_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.URLField(),
        ),
    ]
