# Generated by Django 5.1.2 on 2025-02-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0011_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('header2', models.TextField(blank=True, null=True)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
