# Generated by Django 5.1.2 on 2025-02-14 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0012_bannercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.masterdata')),
            ],
        ),
    ]
